meeting-join & meeting-leave validation (not tested)
code-one-space/backend-meeting pull request #5
Opened 2022-05-28 13:35 UTC by immi77

da fehlte irgendwie meeting-leave lol

2022-05-28 18:19 UTC, nojomyth-dev requested changes
../fork wird auf dem repo nicht funktionieren

2022-05-29 13:07 UTC, immi77 commented
hab den path angepasst

2022-05-29 13:13 UTC, nojomyth-dev approved these changes
lgtm, noch nicht getestet

2022-05-29 13:13 UTC, nojomyth-dev commented on join-meeting/index.ts
> +    const join = {
Gescheite Variablenbenennung bitte
joinedMember, memberToJoin, etc

2022-05-29 13:13 UTC, merged